name: Snapshot to GCR
on:
  push:
    branches:
      - 4.7.x
env:
  REGION: us-central1
jobs:
  gitHub-actions-wif:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run Tests
        run: ./gradlew starter-api:test starter-web-netty:test starter-gcp-function:shadowJar
      - id: 'auth'
        name: 'Authenticate to Google Cloud' # https://github.com/google-github-actions/auth
        uses: 'google-GitHub-actions/auth@v2.1.7'
        with:
          create_credentials_file: true
          project_id: ${{ secrets.GCLOUD_PROJECT }}
          workload_identity_provider: ${{ secrets.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}
      - name: 'Networking activities'
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud compute firewall-rules list --format="table(
              name,
              network,
              direction,
              priority
          )"
        continue-on-error: true
#      - id: 'deploy-cloud-run'
#        name: 'Deploy Cloud Run Hello World Python App'
#        uses: 'google-GitHub-actions/deploy-cloudrun@v1'
#        with:
#          service: 'hello-world'
#          region: 'us-central1'
#
#
#      - name: 'Use output'
#        run: 'curl "${{ steps.deploy-cloud-run.outputs.url }}"'
#        continue-on-error: true